// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consumption.sql

package storage

import (
	"context"
	"database/sql"
	"time"
)

const createConsumptionLog = `-- name: CreateConsumptionLog :one
INSERT INTO consumption_log (user_id, product_id, day, meal_type, grams)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, product_id, day, meal_type, grams
`

type CreateConsumptionLogParams struct {
	UserID    int64     `json:"user_id"`
	ProductID int64     `json:"product_id"`
	Day       time.Time `json:"day"`
	MealType  string    `json:"meal_type"`
	Grams     float64   `json:"grams"`
}

func (q *Queries) CreateConsumptionLog(ctx context.Context, arg CreateConsumptionLogParams) (ConsumptionLog, error) {
	row := q.db.QueryRowContext(ctx, createConsumptionLog,
		arg.UserID,
		arg.ProductID,
		arg.Day,
		arg.MealType,
		arg.Grams,
	)
	var i ConsumptionLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Day,
		&i.MealType,
		&i.Grams,
	)
	return i, err
}

const listConsumptionByUser = `-- name: ListConsumptionByUser :many
SELECT cl.id, cl.user_id, cl.product_id, cl.day, cl.meal_type, cl.grams, p.id, p.name, p.category, p.kcal_100, p.protein_100, p.fat_100, p.carbs_100, p.tags_csv, p.off_barcode
FROM consumption_log cl
JOIN products p ON p.id = cl.product_id
WHERE cl.user_id = ?
ORDER BY cl.day DESC
`

type ListConsumptionByUserRow struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	ProductID  int64          `json:"product_id"`
	Day        time.Time      `json:"day"`
	MealType   string         `json:"meal_type"`
	Grams      float64        `json:"grams"`
	ID_2       int64          `json:"id_2"`
	Name       string         `json:"name"`
	Category   string         `json:"category"`
	Kcal100    float64        `json:"kcal_100"`
	Protein100 float64        `json:"protein_100"`
	Fat100     float64        `json:"fat_100"`
	Carbs100   float64        `json:"carbs_100"`
	TagsCsv    string         `json:"tags_csv"`
	OffBarcode sql.NullString `json:"off_barcode"`
}

func (q *Queries) ListConsumptionByUser(ctx context.Context, userID int64) ([]ListConsumptionByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listConsumptionByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsumptionByUserRow
	for rows.Next() {
		var i ListConsumptionByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Day,
			&i.MealType,
			&i.Grams,
			&i.ID_2,
			&i.Name,
			&i.Category,
			&i.Kcal100,
			&i.Protein100,
			&i.Fat100,
			&i.Carbs100,
			&i.TagsCsv,
			&i.OffBarcode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsumptionByUserAndDateRange = `-- name: ListConsumptionByUserAndDateRange :many
SELECT cl.id, cl.user_id, cl.product_id, cl.day, cl.meal_type, cl.grams, p.id, p.name, p.category, p.kcal_100, p.protein_100, p.fat_100, p.carbs_100, p.tags_csv, p.off_barcode
FROM consumption_log cl
JOIN products p ON p.id = cl.product_id
WHERE cl.user_id = ? AND cl.day >= ? AND cl.day <= ?
ORDER BY cl.day
`

type ListConsumptionByUserAndDateRangeParams struct {
	UserID int64     `json:"user_id"`
	Day    time.Time `json:"day"`
	Day_2  time.Time `json:"day_2"`
}

type ListConsumptionByUserAndDateRangeRow struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	ProductID  int64          `json:"product_id"`
	Day        time.Time      `json:"day"`
	MealType   string         `json:"meal_type"`
	Grams      float64        `json:"grams"`
	ID_2       int64          `json:"id_2"`
	Name       string         `json:"name"`
	Category   string         `json:"category"`
	Kcal100    float64        `json:"kcal_100"`
	Protein100 float64        `json:"protein_100"`
	Fat100     float64        `json:"fat_100"`
	Carbs100   float64        `json:"carbs_100"`
	TagsCsv    string         `json:"tags_csv"`
	OffBarcode sql.NullString `json:"off_barcode"`
}

func (q *Queries) ListConsumptionByUserAndDateRange(ctx context.Context, arg ListConsumptionByUserAndDateRangeParams) ([]ListConsumptionByUserAndDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listConsumptionByUserAndDateRange, arg.UserID, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsumptionByUserAndDateRangeRow
	for rows.Next() {
		var i ListConsumptionByUserAndDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Day,
			&i.MealType,
			&i.Grams,
			&i.ID_2,
			&i.Name,
			&i.Category,
			&i.Kcal100,
			&i.Protein100,
			&i.Fat100,
			&i.Carbs100,
			&i.TagsCsv,
			&i.OffBarcode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
