// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fridge.sql

package storage

import (
	"context"
	"database/sql"
)

const createFridgeItem = `-- name: CreateFridgeItem :one
INSERT INTO fridge_items (user_id, product_id, quantity_g, expiry_date)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, product_id, quantity_g, expiry_date
`

type CreateFridgeItemParams struct {
	UserID     int64        `json:"user_id"`
	ProductID  int64        `json:"product_id"`
	QuantityG  float64      `json:"quantity_g"`
	ExpiryDate sql.NullTime `json:"expiry_date"`
}

func (q *Queries) CreateFridgeItem(ctx context.Context, arg CreateFridgeItemParams) (FridgeItem, error) {
	row := q.db.QueryRowContext(ctx, createFridgeItem,
		arg.UserID,
		arg.ProductID,
		arg.QuantityG,
		arg.ExpiryDate,
	)
	var i FridgeItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.QuantityG,
		&i.ExpiryDate,
	)
	return i, err
}

const deleteFridgeItem = `-- name: DeleteFridgeItem :exec
DELETE FROM fridge_items WHERE id = ? AND user_id = ?
`

type DeleteFridgeItemParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteFridgeItem(ctx context.Context, arg DeleteFridgeItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteFridgeItem, arg.ID, arg.UserID)
	return err
}

const getFridgeItemByID = `-- name: GetFridgeItemByID :one
SELECT fi.id, fi.user_id, fi.product_id, fi.quantity_g, fi.expiry_date, p.id, p.name, p.category, p.kcal_100, p.protein_100, p.fat_100, p.carbs_100, p.tags_csv, p.off_barcode
FROM fridge_items fi
JOIN products p ON p.id = fi.product_id
WHERE fi.id = ? AND fi.user_id = ?
`

type GetFridgeItemByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetFridgeItemByIDRow struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	ProductID  int64          `json:"product_id"`
	QuantityG  float64        `json:"quantity_g"`
	ExpiryDate sql.NullTime   `json:"expiry_date"`
	ID_2       int64          `json:"id_2"`
	Name       string         `json:"name"`
	Category   string         `json:"category"`
	Kcal100    float64        `json:"kcal_100"`
	Protein100 float64        `json:"protein_100"`
	Fat100     float64        `json:"fat_100"`
	Carbs100   float64        `json:"carbs_100"`
	TagsCsv    string         `json:"tags_csv"`
	OffBarcode sql.NullString `json:"off_barcode"`
}

func (q *Queries) GetFridgeItemByID(ctx context.Context, arg GetFridgeItemByIDParams) (GetFridgeItemByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFridgeItemByID, arg.ID, arg.UserID)
	var i GetFridgeItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.QuantityG,
		&i.ExpiryDate,
		&i.ID_2,
		&i.Name,
		&i.Category,
		&i.Kcal100,
		&i.Protein100,
		&i.Fat100,
		&i.Carbs100,
		&i.TagsCsv,
		&i.OffBarcode,
	)
	return i, err
}

const listFridgeItems = `-- name: ListFridgeItems :many
SELECT fi.id, fi.user_id, fi.product_id, fi.quantity_g, fi.expiry_date, p.id, p.name, p.category, p.kcal_100, p.protein_100, p.fat_100, p.carbs_100, p.tags_csv, p.off_barcode
FROM fridge_items fi
JOIN products p ON p.id = fi.product_id
WHERE fi.user_id = ?
ORDER BY fi.id
`

type ListFridgeItemsRow struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	ProductID  int64          `json:"product_id"`
	QuantityG  float64        `json:"quantity_g"`
	ExpiryDate sql.NullTime   `json:"expiry_date"`
	ID_2       int64          `json:"id_2"`
	Name       string         `json:"name"`
	Category   string         `json:"category"`
	Kcal100    float64        `json:"kcal_100"`
	Protein100 float64        `json:"protein_100"`
	Fat100     float64        `json:"fat_100"`
	Carbs100   float64        `json:"carbs_100"`
	TagsCsv    string         `json:"tags_csv"`
	OffBarcode sql.NullString `json:"off_barcode"`
}

func (q *Queries) ListFridgeItems(ctx context.Context, userID int64) ([]ListFridgeItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFridgeItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFridgeItemsRow
	for rows.Next() {
		var i ListFridgeItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.QuantityG,
			&i.ExpiryDate,
			&i.ID_2,
			&i.Name,
			&i.Category,
			&i.Kcal100,
			&i.Protein100,
			&i.Fat100,
			&i.Carbs100,
			&i.TagsCsv,
			&i.OffBarcode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFridgeItem = `-- name: UpdateFridgeItem :one
UPDATE fridge_items
SET quantity_g = ?1, expiry_date = ?2
WHERE id = ?3 AND user_id = ?4
RETURNING id, user_id, product_id, quantity_g, expiry_date
`

type UpdateFridgeItemParams struct {
	QuantityG  float64      `json:"quantity_g"`
	ExpiryDate sql.NullTime `json:"expiry_date"`
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
}

func (q *Queries) UpdateFridgeItem(ctx context.Context, arg UpdateFridgeItemParams) (FridgeItem, error) {
	row := q.db.QueryRowContext(ctx, updateFridgeItem,
		arg.QuantityG,
		arg.ExpiryDate,
		arg.ID,
		arg.UserID,
	)
	var i FridgeItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.QuantityG,
		&i.ExpiryDate,
	)
	return i, err
}
