// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"
	"time"
)

type ConsumptionLog struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	ProductID int64     `json:"product_id"`
	Day       time.Time `json:"day"`
	MealType  string    `json:"meal_type"`
	Grams     float64   `json:"grams"`
}

type FridgeItem struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	ProductID  int64        `json:"product_id"`
	QuantityG  float64      `json:"quantity_g"`
	ExpiryDate sql.NullTime `json:"expiry_date"`
}

type Product struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Category   string         `json:"category"`
	Kcal100    float64        `json:"kcal_100"`
	Protein100 float64        `json:"protein_100"`
	Fat100     float64        `json:"fat_100"`
	Carbs100   float64        `json:"carbs_100"`
	TagsCsv    string         `json:"tags_csv"`
	OffBarcode sql.NullString `json:"off_barcode"`
}

type User struct {
	ID           int64   `json:"id"`
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
	Name         string  `json:"name"`
	Sex          string  `json:"sex"`
	Age          int64   `json:"age"`
	WeightKg     float64 `json:"weight_kg"`
	HeightCm     float64 `json:"height_cm"`
	Activity     string  `json:"activity"`
	Goal         string  `json:"goal"`
	PrefsCsv     string  `json:"prefs_csv"`
}
