// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package storage

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, category, kcal_100, protein_100, fat_100, carbs_100, tags_csv, off_barcode)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, category, kcal_100, protein_100, fat_100, carbs_100, tags_csv, off_barcode
`

type CreateProductParams struct {
	Name       string         `json:"name"`
	Category   string         `json:"category"`
	Kcal100    float64        `json:"kcal_100"`
	Protein100 float64        `json:"protein_100"`
	Fat100     float64        `json:"fat_100"`
	Carbs100   float64        `json:"carbs_100"`
	TagsCsv    string         `json:"tags_csv"`
	OffBarcode sql.NullString `json:"off_barcode"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Category,
		arg.Kcal100,
		arg.Protein100,
		arg.Fat100,
		arg.Carbs100,
		arg.TagsCsv,
		arg.OffBarcode,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Kcal100,
		&i.Protein100,
		&i.Fat100,
		&i.Carbs100,
		&i.TagsCsv,
		&i.OffBarcode,
	)
	return i, err
}

const getProductByBarcode = `-- name: GetProductByBarcode :one
SELECT id, name, category, kcal_100, protein_100, fat_100, carbs_100, tags_csv, off_barcode FROM products WHERE off_barcode = ?
`

func (q *Queries) GetProductByBarcode(ctx context.Context, offBarcode sql.NullString) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByBarcode, offBarcode)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Kcal100,
		&i.Protein100,
		&i.Fat100,
		&i.Carbs100,
		&i.TagsCsv,
		&i.OffBarcode,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, category, kcal_100, protein_100, fat_100, carbs_100, tags_csv, off_barcode FROM products WHERE id = ?
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Kcal100,
		&i.Protein100,
		&i.Fat100,
		&i.Carbs100,
		&i.TagsCsv,
		&i.OffBarcode,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT id, name, category, kcal_100, protein_100, fat_100, carbs_100, tags_csv, off_barcode FROM products WHERE name = ?
`

func (q *Queries) GetProductByName(ctx context.Context, name string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByName, name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Kcal100,
		&i.Protein100,
		&i.Fat100,
		&i.Carbs100,
		&i.TagsCsv,
		&i.OffBarcode,
	)
	return i, err
}

const getProductCount = `-- name: GetProductCount :one
SELECT COUNT(*) FROM products
`

func (q *Queries) GetProductCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProductCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, category, kcal_100, protein_100, fat_100, carbs_100, tags_csv, off_barcode FROM products ORDER BY name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Kcal100,
			&i.Protein100,
			&i.Fat100,
			&i.Carbs100,
			&i.TagsCsv,
			&i.OffBarcode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, name, category, kcal_100, protein_100, fat_100, carbs_100, tags_csv, off_barcode FROM products WHERE name LIKE ? ORDER BY name
`

func (q *Queries) SearchProducts(ctx context.Context, name string) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Kcal100,
			&i.Protein100,
			&i.Fat100,
			&i.Carbs100,
			&i.TagsCsv,
			&i.OffBarcode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
