// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateConsumptionLog(ctx context.Context, arg CreateConsumptionLogParams) (ConsumptionLog, error)
	CreateFridgeItem(ctx context.Context, arg CreateFridgeItemParams) (FridgeItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFridgeItem(ctx context.Context, arg DeleteFridgeItemParams) error
	GetFridgeItemByID(ctx context.Context, arg GetFridgeItemByIDParams) (GetFridgeItemByIDRow, error)
	GetProductByBarcode(ctx context.Context, offBarcode sql.NullString) (Product, error)
	GetProductByID(ctx context.Context, id int64) (Product, error)
	GetProductByName(ctx context.Context, name string) (Product, error)
	GetProductCount(ctx context.Context) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserCount(ctx context.Context) (int64, error)
	ListConsumptionByUser(ctx context.Context, userID int64) ([]ListConsumptionByUserRow, error)
	ListConsumptionByUserAndDateRange(ctx context.Context, arg ListConsumptionByUserAndDateRangeParams) ([]ListConsumptionByUserAndDateRangeRow, error)
	ListFridgeItems(ctx context.Context, userID int64) ([]ListFridgeItemsRow, error)
	ListProducts(ctx context.Context) ([]Product, error)
	SearchProducts(ctx context.Context, name string) ([]Product, error)
	UpdateFridgeItem(ctx context.Context, arg UpdateFridgeItemParams) (FridgeItem, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
