// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package storage

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, sex, age, weight_kg, height_cm, activity, goal, prefs_csv)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, email, password_hash, name, sex, age, weight_kg, height_cm, activity, goal, prefs_csv
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
	Name         string  `json:"name"`
	Sex          string  `json:"sex"`
	Age          int64   `json:"age"`
	WeightKg     float64 `json:"weight_kg"`
	HeightCm     float64 `json:"height_cm"`
	Activity     string  `json:"activity"`
	Goal         string  `json:"goal"`
	PrefsCsv     string  `json:"prefs_csv"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Sex,
		arg.Age,
		arg.WeightKg,
		arg.HeightCm,
		arg.Activity,
		arg.Goal,
		arg.PrefsCsv,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Sex,
		&i.Age,
		&i.WeightKg,
		&i.HeightCm,
		&i.Activity,
		&i.Goal,
		&i.PrefsCsv,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, sex, age, weight_kg, height_cm, activity, goal, prefs_csv FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Sex,
		&i.Age,
		&i.WeightKg,
		&i.HeightCm,
		&i.Activity,
		&i.Goal,
		&i.PrefsCsv,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, sex, age, weight_kg, height_cm, activity, goal, prefs_csv FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Sex,
		&i.Age,
		&i.WeightKg,
		&i.HeightCm,
		&i.Activity,
		&i.Goal,
		&i.PrefsCsv,
	)
	return i, err
}

const getUserCount = `-- name: GetUserCount :one
SELECT COUNT(*) FROM users
`

func (q *Queries) GetUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = COALESCE(?1, name),
    sex = COALESCE(?2, sex),
    age = COALESCE(?3, age),
    weight_kg = COALESCE(?4, weight_kg),
    height_cm = COALESCE(?5, height_cm),
    activity = COALESCE(?6, activity),
    goal = COALESCE(?7, goal),
    prefs_csv = COALESCE(?8, prefs_csv),
    password_hash = COALESCE(?9, password_hash)
WHERE id = ?10
RETURNING id, email, password_hash, name, sex, age, weight_kg, height_cm, activity, goal, prefs_csv
`

type UpdateUserParams struct {
	Name         string  `json:"name"`
	Sex          string  `json:"sex"`
	Age          int64   `json:"age"`
	WeightKg     float64 `json:"weight_kg"`
	HeightCm     float64 `json:"height_cm"`
	Activity     string  `json:"activity"`
	Goal         string  `json:"goal"`
	PrefsCsv     string  `json:"prefs_csv"`
	PasswordHash string  `json:"password_hash"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.Sex,
		arg.Age,
		arg.WeightKg,
		arg.HeightCm,
		arg.Activity,
		arg.Goal,
		arg.PrefsCsv,
		arg.PasswordHash,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Sex,
		&i.Age,
		&i.WeightKg,
		&i.HeightCm,
		&i.Activity,
		&i.Goal,
		&i.PrefsCsv,
	)
	return i, err
}
